title: Stuff I found hard to google answers to
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://oliverculleydelange.github.io" # the base hostname & protocol for your site
github_username:  oliverculleydelange

# Build settings
markdown: kramdown
theme: minima
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"