# https://mmistakes.github.io/minimal-mistakes/docs/configuration/


remote_theme             : "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

locale                   : "en-GB"
title                    : "oliverdelange"
title_separator          : "|"
description              : "A blog I probably won't keep up to date (yep, confirmed)"
url                      : "https://oliverdelange.co.uk" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/

comments:
  provider               : "facebook" 
  # https://developers.facebook.com/docs/plugins/comments
  facebook:
    appid                : "1159322334182605"

analytics:
  provider               : "google"
  google:
    tracking_id          : "UA-40491769-1"


author:
  bio    : "A blog that I probably won't keep up to date (confirmed)"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/OliverCulleyDeLange"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/oliverculleydelange/"
    - label: "Stackoverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/3014299/oliverdelange"

include:
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test

keep_files:
  - .git
  - .svn

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/